/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.integradorpa2.igu.Gatos;

import com.mycompany.integradorpa2.dao.GatoDAO;
import com.mycompany.integradorpa2.dao.GatoDAOJpa;
import com.mycompany.integradorpa2.dao.ZonaDAO;
import com.mycompany.integradorpa2.dao.ZonaDAOJpa;
import com.mycompany.integradorpa2.igu.Main.Cruds;
import com.mycompany.integradorpa2.igu.Main.Navigator;
import com.mycompany.integradorpa2.logica.Gato;
import com.mycompany.integradorpa2.logica.Zona;
import com.mycompany.integradorpa2.logica.enums.EstadoSalud;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author Usuario
 */
public class CreateGato extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateGato.class.getName());

    /**
     * Creates new form CreateGato
     */
    
    private final GatoDAO gatoDao = new GatoDAOJpa();
    private final ZonaDAO zonaDao = new ZonaDAOJpa(); 
    public CreateGato() {
        initComponents();
            setLocationRelativeTo(null);
        // 2.1. Estado de salud
        comboSalud.setModel(new DefaultComboBoxModel<>(
            Arrays.stream(EstadoSalud.values())
                  .map(EstadoSalud::name)   // enum -> "TEXTO"
                  .toArray(String[]::new)
        ));
        EstadoSalud estado = EstadoSalud.valueOf((String) comboSalud.getSelectedItem()); 
       
        // 2.2. Adoptado Sí/No
        comboAdoptado.setModel(new DefaultComboBoxModel<>(new String[]{"No", "Sí"}));

        // 2.3. Zonas
        cargarZonas();

        // 2.4. Spinner edad (0..40)
        spinnerEdad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 40, 1));
        

        
    }
    
    private java.util.List<Zona> zonasCargadas;

    private void cargarZonas() {
        zonasCargadas = zonaDao.listarTodos(); // obtenemos la lista real desde BD
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Zona z : zonasCargadas) {
            model.addElement(z.getNombreZona()); // SOLO mostramos el nombre
        }
        comboZona.setModel(model); // comboZona es JComboBox<String>
}   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbltitulo2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblRaza = new javax.swing.JLabel();
        lblAdoptado = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblZona = new javax.swing.JLabel();
        lblSalud = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        spinnerEdad = new javax.swing.JSpinner();
        txtRaza = new javax.swing.JTextField();
        comboAdoptado = new javax.swing.JComboBox<>();
        comboSalud = new javax.swing.JComboBox<>();
        comboZona = new javax.swing.JComboBox<>();
        botonSalir = new javax.swing.JButton();
        botonCrear = new javax.swing.JButton();

        lbltitulo1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbltitulo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitulo1.setText("Crud Menu");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbltitulo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitulo2.setText("Crear Gato");

        lblNombre.setText("Nombre:");

        lblRaza.setText("Raza:");

        lblAdoptado.setText("Adoptado:");

        lblEdad.setText("Edad:");

        lblZona.setText("Zona:");

        lblSalud.setText("Estado de Salud:");

        comboAdoptado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboSalud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSaludActionPerformed(evt);
            }
        });

        comboZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonCrear.setText("Crear");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCrear)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbltitulo2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombre)
                                .addComponent(lblRaza)
                                .addComponent(lblEdad))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtRaza, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(spinnerEdad, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSalud)
                                .addComponent(lblAdoptado)
                                .addComponent(lblZona))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboAdoptado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbltitulo2)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaza)
                    .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(spinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalud)
                    .addComponent(comboSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdoptado)
                    .addComponent(comboAdoptado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZona)
                    .addComponent(comboZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSaludActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSaludActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        Navigator.go(this, new GatosCRUD());
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
            // TODO add your handling code here:
                try {
        String nombre = txtNombre.getText().trim();
        String raza   = txtRaza.getText().trim();
        int    edad   = (Integer) spinnerEdad.getValue();

        // String -> Enum
        EstadoSalud estado = EstadoSalud.valueOf((String) comboSalud.getSelectedItem());

        // String -> boolean
        boolean adoptado = "Sí".equals(comboAdoptado.getSelectedItem());

        // Índice -> Zona
        int idx = comboZona.getSelectedIndex();
        if (idx < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccioná una zona.");
            return;
        }
        Zona zona = zonasCargadas.get(idx);

        // Validaciones mínimas
        if (nombre.isEmpty()) { javax.swing.JOptionPane.showMessageDialog(this, "Nombre obligatorio."); return; }
        if (edad < 0) { javax.swing.JOptionPane.showMessageDialog(this, "Edad inválida."); return; }

        // Armar entidad y persistir
        Gato g = new Gato();
        g.setNombre(nombre);
        g.setRaza(raza);
        g.setEdad(edad);
        g.setEstadoDeSalud(estado);
        g.setAdoptado(adoptado);
        g.setZona(zona);

        gatoDao.crear(g);

        javax.swing.JOptionPane.showMessageDialog(this, "Gato creado. ID: " + g.getId());
        limpiar();

    } catch (IllegalArgumentException iae) {
        // Esto salta si valueOf no encuentra un nombre de enum válido
        javax.swing.JOptionPane.showMessageDialog(this,
            "Estado de salud inválido: " + comboSalud.getSelectedItem(),
            "Datos inválidos", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error guardando el gato: " + ex.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_botonCrearActionPerformed

    private void limpiar() {
    txtNombre.setText("");
    txtRaza.setText("");
    spinnerEdad.setValue(0);
    comboSalud.setSelectedIndex(0);
    comboAdoptado.setSelectedIndex(0);
    if (comboZona.getItemCount() > 0) comboZona.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreateGato().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> comboAdoptado;
    private javax.swing.JComboBox<String> comboSalud;
    private javax.swing.JComboBox<String> comboZona;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdoptado;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JLabel lblSalud;
    private javax.swing.JLabel lblZona;
    private javax.swing.JLabel lbltitulo1;
    private javax.swing.JLabel lbltitulo2;
    private javax.swing.JSpinner spinnerEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables
}
