/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.integradorpa2.igu.Gatos;

import com.mycompany.integradorpa2.igu.Gatos.DeleteGato;
import com.mycompany.integradorpa2.igu.Gatos.CreateGato;
import com.mycompany.integradorpa2.igu.Main.Cruds;
import com.mycompany.integradorpa2.igu.Main.Navigator;

/**
 *
 * @author Usuario
 */
public class GatosCRUD extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GatosCRUD.class.getName());

    /**
     * Creates new form GatosCRUD
     */
    public GatosCRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        botonReadGato = new javax.swing.JButton();
        botonUpdateGato = new javax.swing.JButton();
        botonDeleteGato = new javax.swing.JButton();
        botonCreateGato = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitulo.setText("Gatos CRUD");

        botonReadGato.setText("Read");
        botonReadGato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonReadGatoMouseClicked(evt);
            }
        });
        botonReadGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReadGatoActionPerformed(evt);
            }
        });

        botonUpdateGato.setText("Update");
        botonUpdateGato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonUpdateGatoMouseClicked(evt);
            }
        });
        botonUpdateGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUpdateGatoActionPerformed(evt);
            }
        });

        botonDeleteGato.setText("Delete");
        botonDeleteGato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDeleteGatoMouseClicked(evt);
            }
        });
        botonDeleteGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDeleteGatoActionPerformed(evt);
            }
        });

        botonCreateGato.setText("Create");
        botonCreateGato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCreateGatoMouseClicked(evt);
            }
        });
        botonCreateGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCreateGatoActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonUpdateGato, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonCreateGato, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonReadGato, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonDeleteGato, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(296, 296, 296)
                                .addComponent(lbltitulo)))
                        .addGap(0, 194, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lbltitulo)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCreateGato, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonReadGato, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonDeleteGato, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonUpdateGato, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCreateGatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCreateGatoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCreateGatoMouseClicked

    private void botonReadGatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReadGatoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonReadGatoMouseClicked

    private void botonUpdateGatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonUpdateGatoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonUpdateGatoMouseClicked

    private void botonDeleteGatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDeleteGatoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonDeleteGatoMouseClicked

    private void botonCreateGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCreateGatoActionPerformed
        // TODO add your handling code here:
        Navigator.go(this, new CreateGato());
    }//GEN-LAST:event_botonCreateGatoActionPerformed

    private void botonReadGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReadGatoActionPerformed
        // TODO add your handling code here:
        Navigator.go(this, new ReadGato());
    }//GEN-LAST:event_botonReadGatoActionPerformed

    private void botonUpdateGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUpdateGatoActionPerformed
        // TODO add your handling code here:
        Navigator.go(this, new UpdateGato());
    }//GEN-LAST:event_botonUpdateGatoActionPerformed

    private void botonDeleteGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDeleteGatoActionPerformed
        // TODO add your handling code here:
         Navigator.go(this, new DeleteGato());
    }//GEN-LAST:event_botonDeleteGatoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          Navigator.go(this, new Cruds());
    }//GEN-LAST:event_jButton1ActionPerformed






    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GatosCRUD().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCreateGato;
    private javax.swing.JButton botonDeleteGato;
    private javax.swing.JButton botonReadGato;
    private javax.swing.JButton botonUpdateGato;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbltitulo;
    // End of variables declaration//GEN-END:variables
}
