/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.integradorpa2.igu.Gatos;

import com.mycompany.integradorpa2.dao.GatoDAO;
import com.mycompany.integradorpa2.dao.GatoDAOJpa;
import com.mycompany.integradorpa2.dao.ZonaDAO;
import com.mycompany.integradorpa2.dao.ZonaDAOJpa;
import com.mycompany.integradorpa2.igu.Main.Navigator;
import com.mycompany.integradorpa2.logica.Gato;
import com.mycompany.integradorpa2.logica.Zona;
import com.mycompany.integradorpa2.logica.enums.EstadoSalud;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class UpdateGato extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateGato.class.getName());

    /**
     * Creates new form UpdateGato
     */
    public UpdateGato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbltitulo2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblRaza = new javax.swing.JLabel();
        txtRaza = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        spinnerEdad = new javax.swing.JSpinner();
        lblSalud = new javax.swing.JLabel();
        comboSalud = new javax.swing.JComboBox<>();
        lblAdoptado = new javax.swing.JLabel();
        comboAdoptado = new javax.swing.JComboBox<>();
        comboZona = new javax.swing.JComboBox<>();
        lblZona = new javax.swing.JLabel();
        botonActualizar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbltitulo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitulo2.setText("Actualizar Gatos");

        lblNombre.setText("Nombre:");

        lblRaza.setText("Raza:");

        lblEdad.setText("Edad:");

        lblSalud.setText("Estado de Salud:");

        comboSalud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSaludActionPerformed(evt);
            }
        });

        lblAdoptado.setText("Adoptado:");

        comboAdoptado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblZona.setText("Zona:");

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonActualizar)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNombre)
                                        .addComponent(lblRaza)
                                        .addComponent(lblEdad))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtRaza, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(spinnerEdad, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSalud)
                                        .addComponent(lblAdoptado)
                                        .addComponent(lblZona))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(comboZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboAdoptado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbltitulo2)
                        .addGap(0, 166, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbltitulo2)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaza)
                    .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(spinnerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalud)
                    .addComponent(comboSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdoptado)
                    .addComponent(comboAdoptado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZona)
                    .addComponent(comboZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        Navigator.go(this, new GatosCRUD());
    }//GEN-LAST:event_botonSalirActionPerformed
    
    private final GatoDAO gatoDao = new GatoDAOJpa();
    private Gato gato; // el gato que vamos a editar
    private final ZonaDAO zonaDao = new ZonaDAOJpa();
    private List<Zona> zonasCargadas = new ArrayList<>(); 

    public UpdateGato(Long id) {
        initComponents();
        setLocationRelativeTo(null);

        // Cargar combos (mismo criterio que en Create)
        cargarComboSaludComoStrings();
        cargarComboAdoptado();
        cargarZonasComoNombres();

        // Traer el gato por id (tu DAO devuelve Optional)
        Optional<Gato> opt = gatoDao.buscarPorId(id);
        if (opt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existe un gato con ID " + id);
            dispose();
            return;
        }
        gato = opt.get();

        // Cargar datos en campos
        txtNombre.setText(nvl(gato.getNombre()));
        txtRaza.setText(nvl(gato.getRaza()));
        spinnerEdad.setValue(gato.getEdad() != null ? gato.getEdad() : 0);

        // Salud: enum -> String (name)
        comboSalud.setSelectedItem(
            gato.getEstadoDeSalud() != null ? gato.getEstadoDeSalud().name() : null
        );

        // Adoptado: boolean -> "Sí"/"No"
        comboAdoptado.setSelectedItem(gato.isAdoptado() ? "Sí" : "No");

        // Zona: seleccionar por ID dentro de la lista
        if (gato.getZona() != null) {
            Long idZona = gato.getZona().getId();
            for (int i = 0; i < zonasCargadas.size(); i++) {
                if (zonasCargadas.get(i).getId().equals(idZona)) {
                    comboZona.setSelectedIndex(i);
                    break;
                }
            }
        }
    }
    
    private void cargarComboSaludComoStrings() {
        // Muestra los nombres de los enums
        String[] items = Arrays.stream(EstadoSalud.values())
                               .map(EstadoSalud::name)
                               .toArray(String[]::new);
        comboSalud.setModel(new DefaultComboBoxModel<>(items));
    }

    private void cargarComboAdoptado() {
        comboAdoptado.setModel(new DefaultComboBoxModel<>(new String[]{"No", "Sí"}));
    }

    private void cargarZonasComoNombres() {
        zonasCargadas = zonaDao.listarTodos();                 // lista real
        DefaultComboBoxModel<String> m = new DefaultComboBoxModel<>();
        for (Zona z : zonasCargadas) m.addElement(nvl(z.getNombreZona()));
        comboZona.setModel(m);
    }

    private static String nvl(String s) { return s == null ? "" : s; }

    
    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        // TODO add your handling code here:
         try {
            if (gato == null) {
                JOptionPane.showMessageDialog(this, "Primero cargá un gato válido.");
                return;
            }

            // Validaciones simples
            String nombre = txtNombre.getText().trim();
            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El nombre es obligatorio.");
                return;
            }

            // Tomar valores de UI -> Entidad
            gato.setNombre(nombre);
            gato.setRaza(txtRaza.getText().trim());
            gato.setEdad((Integer) spinnerEdad.getValue());

            // String -> Enum
            String saludStr = (String) comboSalud.getSelectedItem();
            gato.setEstadoDeSalud(saludStr != null ? EstadoSalud.valueOf(saludStr) : null);

            // "Sí"/"No" -> boolean
            boolean adoptado = "Sí".equals(comboAdoptado.getSelectedItem());
            gato.setAdoptado(adoptado);

            // Índice -> Zona real
            int idxZona = comboZona.getSelectedIndex();
            gato.setZona(idxZona >= 0 ? zonasCargadas.get(idxZona) : null);

            // Persistir
            gatoDao.actualizar(gato);

            JOptionPane.showMessageDialog(this, "Gato actualizado correctamente.");
            dispose();

        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(this,
                "Estado de salud inválido: " + comboSalud.getSelectedItem(),
                "Datos inválidos", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Error al actualizar: " + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void comboSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSaludActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSaludActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UpdateGato().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> comboAdoptado;
    private javax.swing.JComboBox<String> comboSalud;
    private javax.swing.JComboBox<String> comboZona;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdoptado;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JLabel lblSalud;
    private javax.swing.JLabel lblZona;
    private javax.swing.JLabel lbltitulo2;
    private javax.swing.JSpinner spinnerEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables
}
