/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.integradorpa2.igu.Operaciones;

import com.mycompany.integradorpa2.igu.Main.Navigator;
import com.mycompany.integradorpa2.igu.Main.Operaciones;

/**
 *
 * @author Usuario
 */
public class InicioSesion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InicioSesion.class.getName());

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        setLocationRelativeTo(null);

        // Asegurar que estén en el ButtonGroup en el diseñador (ya lo hiciste)
        // y asignar action commands para leer fácil el rol
        botonVeterinario.setActionCommand("VETERINARIO");
        botonVoluntario.setActionCommand("VOLUNTARIO");
        botonFamilia.setActionCommand("FAMILIA");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRol = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblContraseña = new javax.swing.JLabel();
        BotonEntrar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        botonVeterinario = new javax.swing.JRadioButton();
        botonFamilia = new javax.swing.JRadioButton();
        botonVoluntario = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbltitulo.setText("Happy Paws");

        lblUsuario.setText("Usuario:");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        lblContraseña.setText("Contraseña:");

        BotonEntrar.setText("Entrar");
        BotonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEntrarMouseClicked(evt);
            }
        });
        BotonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEntrarActionPerformed(evt);
            }
        });

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        grupoRol.add(botonVeterinario);
        botonVeterinario.setText("Veterinario");

        grupoRol.add(botonFamilia);
        botonFamilia.setText("Familia");
        botonFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFamiliaActionPerformed(evt);
            }
        });

        grupoRol.add(botonVoluntario);
        botonVoluntario.setText("Voluntario");
        botonVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVoluntarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(lbltitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonSalir)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonEntrar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonVeterinario)
                        .addGap(35, 35, 35)
                        .addComponent(botonVoluntario)
                        .addGap(28, 28, 28)
                        .addComponent(botonFamilia)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVeterinario)
                    .addComponent(botonVoluntario)
                    .addComponent(botonFamilia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonEntrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(BotonSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void BotonEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEntrarMouseClicked
        
    }//GEN-LAST:event_BotonEntrarMouseClicked

    private void BotonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEntrarActionPerformed
        // 1) Validaciones de campos
        String usuario = txtUsuario.getText().trim();
        String pass = new String(txtPassword.getPassword());

        if (usuario.isEmpty() || pass.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Completá usuario y contraseña.");
            return;
        }

        if (grupoRol.getSelection() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Seleccioná un rol (Veterinario / Voluntario / Familia).");
            return;
        }

        String rol = grupoRol.getSelection().getActionCommand(); // "VETERINARIO" | "VOLUNTARIO" | "FAMILIA"

        try {
            switch (rol) {
                case "VETERINARIO" -> {
                    var dao = new com.mycompany.integradorpa2.dao.VeterinarioDAOJpa();
                    var opt = dao.buscarPorUsuarioYPassword(usuario, pass);
                    if (opt.isPresent()) {
                        var v = opt.get();
                        // Pasás la entidad logueada por si la querés usar en Operaciones
                        new OperacionesVeterinario(v).setVisible(true);
                        dispose();
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Credenciales inválidas para Veterinario.");
                    }
                }

                case "VOLUNTARIO" -> {
                    var dao = new com.mycompany.integradorpa2.dao.VoluntarioDAOJpa();
                    var opt = dao.buscarPorUsuarioYPassword(usuario, pass);
                    if (opt.isPresent()) {
                        var vol = opt.get();
                        new OperacionesVoluntario(vol).setVisible(true);
                        dispose();
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Credenciales inválidas para Voluntario.");
                    }
                }

                case "FAMILIA" -> {
                    var dao = new com.mycompany.integradorpa2.dao.FamiliaDAOJpa();
                    var opt = dao.buscarPorUsuarioYPassword(usuario, pass);
                    if (opt.isPresent()) {
                        var f = opt.get();
                        new OperacionesFamilia(f).setVisible(true);
                        dispose();
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Credenciales inválidas para Familia.");
                    }
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                "Ocurrió un error al iniciar sesión: " + ex.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonEntrarActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        Navigator.go(this, new Operaciones());
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void botonFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFamiliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFamiliaActionPerformed

    private void botonVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVoluntarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVoluntarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InicioSesion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEntrar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JRadioButton botonFamilia;
    private javax.swing.JRadioButton botonVeterinario;
    private javax.swing.JRadioButton botonVoluntario;
    private javax.swing.ButtonGroup grupoRol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
